import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { capture, run } from './exec.js'
import { chainDir, readVersions } from './paths.js'

/** Where compose lives, relative to the Anchor workspace. */
export const composeFile = (root?: string): string => join(chainDir(root), 'docker-compose.yml')

/** The generated env file compose interpolates its build args from. */
export const composeEnvFile = (root?: string): string => join(chainDir(root), 'docker', '.env')

/**
 * Rewrite docker/.env from versions.json.
 *
 * Compose cannot read JSON, and duplicating the pins into the compose file by
 * hand is exactly how an image quietly ends up on a version nobody chose. So
 * this is regenerated before every docker command and gitignored — versions.json
 * stays the single source of truth.
 */
export function writeComposeEnv(root?: string): string {
  const v = readVersions(root)
  const uid = process.getuid?.() ?? 1000
  const gid = process.getgid?.() ?? 1000
  const body = [
    '# GENERATED by `chain` from versions.json. Do not edit; your changes will be lost.',
    `RUST_VERSION=${v.rust}`,
    `AGAVE_VERSION=${v.agave}`,
    `ANCHOR_VERSION=${v.anchor}`,
    `NODE_MAJOR=${v.node}`,
    `CHAIN_UID=${uid}`,
    `CHAIN_GID=${gid}`,
    '',
  ].join('\n')
  const path = composeEnvFile(root)
  mkdirSync(join(path, '..'), { recursive: true })
  writeFileSync(path, body)
  return path
}

/** Is a usable Docker with the compose plugin on this machine? */
export function dockerAvailable(): boolean {
  return capture('docker', ['compose', 'version']) !== null
}

export type RunnerName = 'host' | 'docker'

/**
 * Which runner to use.
 *
 * Docker by default, because the host install is the fragile one. CHAIN_RUNNER
 * forces either way — `host` is the escape hatch when you already have the
 * toolchain installed and want to skip the container round-trip.
 */
export function chosenRunner(env: NodeJS.ProcessEnv = process.env, root?: string): RunnerName {
  const forced = env.CHAIN_RUNNER
  if (forced === 'host' || forced === 'docker') return forced
  if (forced !== undefined) throw new Error(`CHAIN_RUNNER must be "host" or "docker", got "${forced}"`)
  return existsSync(composeFile(root)) && dockerAvailable() ? 'docker' : 'host'
}

/** Base `docker compose` invocation, with the project's file and env pinned. */
export function composeBase(root?: string): string[] {
  return ['compose', '--file', composeFile(root), '--env-file', composeEnvFile(root)]
}

function prepare(root?: string): void {
  writeComposeEnv(root)
  // Compose creates missing bind-mount sources as root, which then locks the
  // container's own user out of writing its deploy keypair.
  mkdirSync(join(chainDir(root), '.solana'), { recursive: true })
}

/** Build (or rebuild) the toolchain image. */
export function imageBuild(opts: { noCache?: boolean; root?: string } = {}): void {
  prepare(opts.root)
  run('docker', [...composeBase(opts.root), 'build', ...(opts.noCache ? ['--no-cache'] : []), 'toolchain'])
}

/** Does the toolchain image exist locally? */
export function imageExists(tag = 'chain-dev:local'): boolean {
  const out = capture('docker', ['image', 'inspect', tag, '--format', '{{.Id}}'])
  return out !== null && out.trim().length > 0
}

/** Run a one-shot command in the toolchain container. */
export function composeRun(cmd: string, args: string[], root?: string): void {
  prepare(root)
  run('docker', [...composeBase(root), 'run', '--rm', 'toolchain', cmd, ...args])
}

/** Run a one-shot command in the toolchain container, capturing stdout. */
export function composeCapture(cmd: string, args: string[], root?: string): string | null {
  prepare(root)
  return capture('docker', [...composeBase(root), 'run', '--rm', '-T', 'toolchain', cmd, ...args])
}

/** The compose project name, which namespaces this repo's containers. */
export function projectName(env: NodeJS.ProcessEnv = process.env): string {
  return env.CHAIN_PROJECT || 'chain'
}

/**
 * A container from a *different* project holding one of our ports, if any.
 *
 * Only one validator can publish 8899, so a second checkout that copied this
 * toolchain cannot run at the same time as the first. Docker's own message for
 * that is "Bind for 127.0.0.1:8899 failed: port is already allocated", which
 * names neither the culprit nor the repo it belongs to.
 */
export function foreignPortHolder(port = 8899, env: NodeJS.ProcessEnv = process.env): string | null {
  const out = capture('docker', ['ps', '--filter', `publish=${port}`, '--format', '{{.Names}}'])
  if (out === null) return null
  const mine = `${projectName(env)}-`
  return out.split('\n').map((s) => s.trim()).find((n) => n.length > 0 && !n.startsWith(mine)) ?? null
}

/** Start the validator service in the background. */
export function composeUpValidator(root?: string): void {
  prepare(root)
  run('docker', [...composeBase(root), 'up', '--detach', 'validator'])
}

/** Stop and remove the stack's containers. Volumes (cargo cache) survive. */
export function composeDown(root?: string): void {
  prepare(root)
  run('docker', [...composeBase(root), 'down', '--remove-orphans'])
}
